// <auto-generated />
using System;
using LoyaltyHub.Loyalty.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoyaltyHub.Loyalty.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LoyaltyDbContext))]
    [Migration("20260904120351_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoyaltyHub.Loyalty.Domain.Entities.DbSeedVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("DbSeedVersions", (string)null);
                });

            modelBuilder.Entity("LoyaltyHub.Loyalty.Domain.Entities.RecentPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ScoreCalculationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScoreCalculationId", "Sequence")
                        .IsUnique();

                    b.ToTable("RecentPurchases", (string)null);
                });

            modelBuilder.Entity("LoyaltyHub.Loyalty.Domain.Entities.ScoreCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseScore")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalScore")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FrequencyBonus")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HighPurchaseBonus")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PurchaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PurchaseCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBonus")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("ScoreCalculations", (string)null);
                });

            modelBuilder.Entity("LoyaltyHub.Loyalty.Domain.Entities.RecentPurchase", b =>
                {
                    b.HasOne("LoyaltyHub.Loyalty.Domain.Entities.ScoreCalculation", "ScoreCalculation")
                        .WithMany("RecentPurchases")
                        .HasForeignKey("ScoreCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoreCalculation");
                });

            modelBuilder.Entity("LoyaltyHub.Loyalty.Domain.Entities.ScoreCalculation", b =>
                {
                    b.Navigation("RecentPurchases");
                });
#pragma warning restore 612, 618
        }
    }
}
